export const ERROR_CODES = [
  "MISSING_REQUIRED_COLUMN",
  "EXTRA_COLUMN",
  "DUPLICATE_HEADER",
  "REQUIRED_VALUE",
  "INVALID_STRING",
  "INVALID_INTEGER",
  "INVALID_NUMBER",
  "INVALID_BOOLEAN",
  "INVALID_DATE",
  "INVALID_DATETIME",
  "VALUE_NOT_ALLOWED",
  "REGEX_MISMATCH",
  "MIN_VALUE",
  "MAX_VALUE",
  "MIN_LENGTH",
  "MAX_LENGTH",
  "NOT_POSITIVE",
  "DUPLICATE_ROW",
  "MALFORMED_FILE",
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];
